development:
  adapter: mysql2
  host: localhost
  username: recipedb
  password: recipedb
  database: recipedb_dev
  encoding: utf8

production:
  adapter: mysql2
  host: localhost
  username: recipedb
  password: recipedb
  database: recipedb
  encoding: utf8

production:
  adapter: mysql2
  host: localhost
  username: recipedb
  password: recipedb
  database: recipedb_test
  encoding: utf8
