# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590469aec87427dbecd4300b66d4c02f11483b038e3cb09826c68f3d473d0935a2173ed828e5e4d883fd43cdf23930b2f97ea8f8f1b1460f06d401c1d2a9f8ba

test:
  secret_key_base: cdaf6504d90ab8607f368620c41822c7852e7649a12e384239fc43788c8ebecf9988ddda9fb38f87262ec70bbf7eee9a1d5fc3dd2141497b5e1706b74ca89c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
